insert into usuario (ID, NIF, COD_COL_ELECTORAL, EMAIL, LOGIN, NOMBRE, PASSWORD, VOTO_ELECTRONICO) values (1, '88888888P', '1', 'adrian@gmail.com', 'adrian', 'adrian', 'adrian', true );
insert into usuario (ID, NIF, COD_COL_ELECTORAL, EMAIL, LOGIN, NOMBRE, PASSWORD, VOTO_ELECTRONICO) values (2, '77777777Q', '1', 'dani@gmail.com', 'dani', 'dani', 'dani', true );
insert into usuario (ID, NIF, COD_COL_ELECTORAL, EMAIL, LOGIN, NOMBRE, PASSWORD, VOTO_ELECTRONICO) values (3, '55555555S', '2', 'eduardo@gmail.com', 'eduardo', 'eduardo', 'eduardo', false);
insert into usuario (ID, NIF, COD_COL_ELECTORAL, EMAIL, LOGIN, NOMBRE, PASSWORD, VOTO_ELECTRONICO) values (4, '11111111L', '3', 'maria@gmail.com', 'maria', 'maria', 'maria', false);
insert into usuario (ID, NIF, COD_COL_ELECTORAL, EMAIL, LOGIN, NOMBRE, PASSWORD, VOTO_ELECTRONICO) values (5, '22222222A', '4', 'jose@gmail.com', 'jose', 'jose', 'jose', false);

insert into colegio_electoral(id,nombre) values (1, 'Ciudad Naranco');
insert into colegio_electoral(id,nombre) values (2, 'La Corredoria');

insert into eleccion(id,nombre) values (1, '27N');
insert into eleccion(id,nombre) values (2, '4A');
insert into eleccion(id,nombre) values (3, '5O');

insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 0, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 0, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (2, 1, 1, 'Nulo');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'Sí');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 1, 'No');
insert into voto (id_colegio,id_eleccion,online,opcion) values (1, 1, 0, 'Sí');

